Add workload identity federation docs
DFE-Digital/dfe-analytics pull request #160
Opened 2024-08-12 16:29 UTC by asatwal

### Context
Add workload identity federation documentation to allow teams to setup on their own projects.

### Trello tickets:
https://trello.com/c/F7WrGYYq

### Changes proposed in this pull request
Documentation only with full WIF instructions.

2024-08-13 13:19 UTC, ericaporter commented on README.md
Maybe `.....Rails app:`

2024-08-13 13:20 UTC, ericaporter commented on README.md
> +
Maybe #### for 3.1

2024-08-13 13:23 UTC, ericaporter commented on docs/google_cloud_bigquery_setup.md
> +
Extra line (unless this follows formatting)

2024-08-13 13:25 UTC, ericaporter commented on docs/google_cloud_bigquery_setup.md
> +If this does not exist then access can be granted with either the [update wif service account permissions ](https://github.com/DFE-Digital/teacher-services-analytics-cloud/blob/main/scripts/gcloud/up
from 'Azure'

2024-08-15 12:35 UTC, ericaporter approved these changes
👍 Looks good

2024-08-15 15:47 UTC, stevenleggdfe requested changes

2024-08-15 15:47 UTC, stevenleggdfe commented on docs/google_cloud_bigquery_setup.md
> +Download the JSON WIF Credentials file either the [create wif client credentials](https://github.com/DFE-Digital/teacher-services-analytics-cloud/blob/main/scripts/gcloud/create-wif-client-credential
Missing a word or two in this sentence I think

2024-08-16 09:10 UTC, stevenleggdfe approved these changes

2024-08-16 09:38 UTC, merged